const nl: Record<string, string> = {
  "Recipe name is required.": "Receptnaam is verplicht.",
  "Failed to save recipe. Please try again.": "Recept opslaan mislukt. Probeer het opnieuw.",
  "Basic Info": "Basisgegevens",
  "Name": "Naam",
  "e.g. Grilled Chicken with Salsa": "bijv. Gegrilde Kip met Salsa",
  "Description": "Beschrijving",
  "A brief description of the dish...": "Een korte beschrijving van het gerecht...",
  "Details": "Details",
  "Cooking time (min)": "Bereidingstijd (min)",
  "Kitchen": "Keuken",
  "Status": "Status",
  "Rating": "Waardering",
  "Ingredients": "Ingrediënten",
  "Add": "Toevoegen",
  "No ingredients yet. Click \"Add\" to get started.": "Nog geen ingrediënten. Klik op \"Toevoegen\" om te beginnen.",
  "Qty": "Aantal",
  "Unit": "Eenheid",
  "Saving...": "Opslaan...",
  "Save Changes": "Wijzigingen Opslaan",
  "Create Recipe": "Recept Aanmaken",
  "to try": "proberen",
  "success": "geslaagd",
  "needs tweak": "aanpassen nodig",
  "failure": "mislukt",
  "archived": "gearchiveerd",
  "Quantity must be greater than 0.": "Hoeveelheid moet groter zijn dan 0.",
  "Ingredient name is required.": "Ingrediëntnaam is verplicht.",
  "Cooking time cannot be negative.": "Bereidingstijd kan niet negatief zijn.",

  "pcs": "stk",
  "tsp": "tl",
  "tbsp": "el",
  "pinch": "snufje",
  "User not found": "Gebruiker niet gevonden",
  "Wrong password": "Ongeldig wachtwoord",
  "Login failed. Please try again.": "Inloggen mislukt. Probeer het opnieuw.",
  "Username": "Gebruikersnaam",
  "Password": "Wachtwoord",
  "Logging in...": "Inloggen...",
  "Login": "Inloggen",
  "Logout": "Uitloggen",
  "Taste tracker": "Smaakmeter",
  "New Recipe": "Nieuw Recept",
  "All": "Alle",
  "No recipes yet.": "Nog geen recepten.",
  "Create your first recipe": "Maak je eerste recept aan",
  "No recipes with status \"{status}\".": "Geen recepten met status \"{status}\".",
  "Delete this recipe?": "Dit recept verwijderen?",
  "Edit": "Bewerk",
  "Delete": "Verwijder",
  "Ingredient": "Ingrediënt",
  "Quantity": "Hoeveelheid",
  "No ingredients listed.": "Geen ingrediënten vermeld.",
  "Back to recipe": "Terug naar recept",
  "Edit Recipe": "Recept Bewerken",
  "Search a kitchen…": "Zoek een keuken…",
  "Clear": "Wissen",
  "Welcome to": "Welkom bij",
  "Built for personal use and development": "Gemaakt voor persoonlijk gebruik en ontwikkeling",
  "Time": "Tijd",
  "Steps": "Stappen",
  "Add step": "Stap toevoegen",
  "No steps yet. Click \"Add step\" to get started.": "Nog geen stappen. Klik op \"Stap toevoegen\" om te beginnen.",
  "Step": "Stap",
  "Search": "Zoeken",
  "Search recipes\u2026": "Zoek recepten\u2026",
  "Search results for \"{q}\"": "Zoekresultaten voor \"{q}\"",
  "No recipes found for \"{q}\".": "Geen recepten gevonden met \"{q}\".",
  "Clear search": "Wis zoekopdracht",
  "Recipe": "Recept",
  "g": "gr",
  "kg": "kg",
  "ml": "ml",
  "l": "l",

  "Workout Studio": "Workout Studio",
  "Resistance": "Krachttraining",
  "Bodyweight": "Lichaamsgewicht",
  "Cardio": "Cardio",
  "Isometric": "Isometrisch",
  "Category": "Categorie",
  "Distance (km)": "Afstand (km)",
  "Time (MM:SS)": "Tijd (MM:SS)",
  "Avg HR (bpm)": "Hartslag (bpm)",
  "RPE (0-10)": "RPE (0-10)",
  "Added weight (kg)": "Extra gewicht (kg)",
  "Added/Assisted (kg)": "Extra/Assisted (kg)",
  "Workouts": "Workouts",
  "Templates": "Sjablonen",
  "New Template": "Nieuw Sjabloon",
  "Template name is required.": "Sjabloonnaam is verplicht.",
  "Exercise name is required.": "Oefeningsnaam is verplicht.",
  "Edit Template": "Sjabloon Bewerken",
  "Create Template": "Sjabloon Aanmaken",
  "Sets": "Sets",
  "Reps": "Herhalingen",
  "Weight": "Gewicht",
  "kg (optional)": "kg (optioneel)",
  "Exercises": "Oefeningen",
  "No exercises yet. Click \"Add\" to get started.": "Nog geen oefeningen. Klik op \"Toevoegen\" om te beginnen.",
  "Add exercise": "Oefening toevoegen",
  "Start workout": "Start training",
  "Quick start": "Snelle start",
  "No templates yet.": "Nog geen sjablonen.",
  "Create your first template": "Maak je eerste sjabloon aan",
  "Active": "Actief",
  "Completed": "Voltooid",
  "No active sessions.": "Geen actieve trainingen.",
  "No completed sessions yet.": "Nog geen voltooide trainingen.",
  "Session": "Training",
  "Duration": "Duur",
  "Notes": "Notities",
  "Complete workout": "Training afronden",
  "Finish": "Afronden",
  "Add set": "Set toevoegen",
  "Set": "Set",
  "Mark set as completed": "Markeer set als voltooid",
  "Complete": "Voltooid",
  "exercise": "oefening",
  "Next": "Volgende",
  "Previous": "Vorige",
  "Exercise": "Oefening",
  "Progress": "Voortgang",
  "History": "Geschiedenis",
  "Personal records": "Persoonlijke records",
  "Best set": "Beste set",
  "Total volume": "Totaal volume",
  "Sessions": "Sessies",
  "No data yet for this exercise.": "Nog geen gegevens voor deze oefening.",
  "Delete this workout?": "Deze training verwijderen?",
  "Delete this template?": "Dit sjabloon verwijderen?",
  "Back to templates": "Terug naar sjablonen",
  "Back to overview": "Terug naar overzicht",
  "Workout Studio Template": "Workout Studio Sjabloon",
  "Choose a template or start fresh": "Kies een sjabloon of begin leeg",
  "or": "of",
  "Start blank workout": "Begin lege training",
  "Started at": "Gestart op",
  "Completed at": "Voltooid op",
  "in progress": "bezig",
  "Toggle history": "Toon geschiedenis",
  "Remove": "Verwijderen",
  "A brief description...": "Een korte beschrijving...",
  "Sets must be at least 1.": "Sets moet minimaal 1 zijn.",
  "Reps must be at least 1.": "Herhalingen moeten minimaal 1 zijn.",
  "Failed to save template. Please try again.": "Sjabloon opslaan mislukt. Probeer het opnieuw.",
  "e.g. Full Body": "bijv. Full Body",
  "No exercises yet.": "Nog geen oefeningen.",
  "No exercises yet. Add one to start.": "Nog geen oefeningen. Voeg er een toe om te beginnen.",
  "Target muscle groups": "Doelspiergroepen",
  "Estimated time (minutes)": "Geschatte tijd (minuten)",
  "Estimated time": "Geschatte tijd",
  "min": "min",
  "Target": "Doel",
  "Done": "Klaar",
  "Finished": "Voltooid",
  "Workout title": "Trainingsnaam",
  "Replace Exercise": "Oefening vervangen",
  "View History": "Geschiedenis bekijken",
  "Workout Review & Edits": "Training Beoordelen & Aanpassen",
  "Duration Editor": "Tijdsduur aanpassen",
  "Performance Summary": "Prestatiesamenvatting",
  "Total volume lifted": "Totaal volume getild",
  "PRs (Personal Records)": "Persoonlijke Records (PR's)",
  "New Record!": "Nieuw Record!",
  "Save": "Opslaan",
  "Discard Workout": "Training weggooien",
  "Are you sure you want to discard this workout session?": "Weet je zeker dat je deze training wilt weggooien?",
  "You have unfinished sets. Mark them as skipped or return to workout?": "Je hebt onafgeronde sets. Wil je deze markeren als overgeslagen of teruggaan naar de training?",
  "Return to workout": "Terug naar training",
  "Finish anyway": "Toch afronden",
  "History for {name}": "Geschiedenis van {name}",
  "Select Exercise to Replace": "Kies oefening ter vervanging",
  "Add Exercise": "Oefening toevoegen",
  "Hours": "Uur",
  "Minutes": "Min",
  "Seconds": "Sec",
  "Reorder": "Volgorde aanpassen",
  "Reorder Exercises": "Oefeningen herordenen",
  "Move Up": "Omhoog",
  "Move Down": "Omlaag",
  "Apply": "Toepassen",
  "Cancel": "Annuleren",
  "Last workout: today": "Laatste training: vandaag",
  "Last workout: yesterday": "Laatste training: gisteren",
  "Last workout: {days} days ago": "Laatste training: {days} dagen geleden",
  "Last workout: no workouts completed yet": "Laatste training: nog geen trainingen voltooid",
  "Total amount of exercises done": "Totaal aantal oefeningen gedaan",
  "Total volume moved": "Totaal volume verplaatst",
  "trainingen voltooid": "trainingen voltooid",
  "was je laatste training": "was je laatste training",
  "geleden was je laatste training": "geleden was je laatste training",
  "oefeningen gedaan": "oefeningen gedaan",
  "workouts gedaan": "workouts gedaan",
  "volume verplaatst": "volume verplaatst",
  "Leave Workout": "Training verlaten",
  "You are currently in an active workout. Are you sure you want to leave?": "Je bent momenteel bezig met een training. Weet je zeker dat je wilt weggaan?",
  "Leave": "Verlaten",
  "barbell": "Barbell",
  "dumbbell": "Dumbbell",
  "kettlebell": "Kettlebell",
  "cable": "Kabel",
  "machine": "Machine",
  "band": "Weerstandsband",
  "none": "Geen",
  "Rest time (sec)": "Rusttijd (sec)",
  "Next milestone": "Volgende mijlpaal",
  "naar volgende mijlpaal": "tot volgende mijlpaal",
  "tot volgende mijlpaal": "tot volgende mijlpaal",
  "Rest": "Rusten",
  "Skip": "Overslaan",
  "Search exercises…": "Zoek oefeningen…",
  "Equipment": "Materiaal",
  "Rest Time": "Rusttijd",
  "Account": "Account",
  "Logged in as": "Ingelogd als",
  "Go to Workouts home": "Naar startpagina trainingen",
  "Go to Recipes home": "Naar startpagina recepten",
  "Resting": "Rusten",
  "seconds": "seconden",
  "sec": "sec",
  "Volume": "Volume",
  "Oefening": "Oefening",
  "All exercises completed!": "Alle oefeningen voltooid!",
  "Good job! Finish your workout to save your results.": "Goed gedaan! Rond je training af om de resultaten op te slaan.",
};



export function t(key: string, params?: Record<string, string>): string {
  let text = nl[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, v);
    }
  }
  return text;
}
