const nl: Record<string, string> = {
  "Recipe name is required.": "Receptnaam is verplicht.",
  "Failed to save recipe. Please try again.": "Recept opslaan mislukt. Probeer het opnieuw.",
  "Basic Info": "Basisgegevens",
  "Name": "Naam",
  "e.g. Grilled Chicken with Salsa": "bijv. Gegrilde Kip met Salsa",
  "Description": "Beschrijving",
  "A brief description of the dish...": "Een korte beschrijving van het gerecht...",
  "Details": "Details",
  "Cooking time (min)": "Bereidingstijd (min)",
  "Kitchen": "Keuken",
  "Status": "Status",
  "Rating": "Waardering",
  "Ingredients": "Ingrediënten",
  "Add": "Toevoegen",
  "No ingredients yet.": "Nog geen ingrediënten.",
  "Add ingredient": "Ingrediënt toevoegen",
  "Qty": "Aantal",
  "Unit": "Eenheid",
  "Saving...": "Opslaan...",
  "Save Changes": "Wijzigingen Opslaan",
  "Create Recipe": "Recept Aanmaken",
  "to try": "proberen",
  "success": "geslaagd",
  "needs tweak": "aanpassen nodig",
  "failure": "mislukt",
  "archived": "gearchiveerd",
  "Quantity must be greater than 0.": "Hoeveelheid moet groter zijn dan 0.",
  "Ingredient name is required.": "Ingrediëntnaam is verplicht.",
  "Cooking time cannot be negative.": "Bereidingstijd kan niet negatief zijn.",

  "pcs": "stk",
  "tsp": "tl",
  "tbsp": "el",
  "pinch": "snufje",
  "User not found": "Gebruiker niet gevonden",
  "Wrong password": "Ongeldig wachtwoord",
  "Login failed. Please try again.": "Inloggen mislukt. Probeer het opnieuw.",
  "Username": "Gebruikersnaam",
  "Password": "Wachtwoord",
  "Logging in...": "Inloggen...",
  "Login": "Inloggen",
  "Logout": "Uitloggen",
  "Taste tracker": "Tast tracker",
  "Recipes and wines": "Recipes & wines",
  "New Recipe": "Nieuw Recept",
  "All": "Alle",
  "No recipes yet.": "Nog geen recepten.",
  "Create your first recipe": "Maak je eerste recept aan",
  "No recipes with status \"{status}\".": "Geen recepten met status \"{status}\".",
  "Delete this recipe?": "Dit recept verwijderen?",
  "This action cannot be undone.": "Dit kan niet ongedaan worden gemaakt.",
  "Edit": "Bewerk",
  "Delete": "Verwijder",
  "Ingredient": "Ingrediënt",
  "Quantity": "Hoeveelheid",
  "No ingredients listed.": "Geen ingrediënten vermeld.",
  "Back to recipe": "Terug naar recept",
  "Edit Recipe": "Recept Bewerken",
  "Search a kitchen…": "Zoek een keuken…",
  "Clear": "Wissen",
  "Welcome to": "Welkom bij",
  "Built for personal use and development": "Gemaakt voor persoonlijk gebruik en ontwikkeling",
  "Time": "Tijd",
  "Steps": "Bereidingswijze",
  "Add step": "Stap toevoegen",
  "No steps yet.": "Nog geen stappen.",
  "Step": "Stap",
  "Search": "Zoeken",
  "Search recipes\u2026": "Zoek recepten\u2026",
  "Search results for \"{q}\"": "Zoekresultaten voor \"{q}\"",
  "No recipes found for \"{q}\".": "Geen recepten gevonden met \"{q}\".",
  "Clear search": "Wis zoekopdracht",
  "Search workouts…": "Zoek trainingen…",
  "Template": "Sjabloon",
  "No sessions found for \"{q}\".": "Geen trainingen gevonden voor \"{q}\".",
  "Recipe": "Recept",
  "Recipes": "Recepten",
  "g": "gr",
  "kg": "kg",
  "ml": "ml",
  "l": "l",

  "Workout Studio": "Workout Studio",
  "Resistance": "Krachttraining",
  "Bodyweight": "Lichaamsgewicht",
  "Cardio": "Cardio",
  "Isometric": "Isometrisch",
  "Category": "Categorie",
  "Distance (km)": "Afstand (km)",
  "Time (MM:SS)": "Tijd (MM:SS)",
  "Avg HR (bpm)": "Hartslag (bpm)",
  "RPE (0-10)": "RPE (0-10)",
  "Added weight (kg)": "Extra gewicht (kg)",
  "Added/Assisted (kg)": "Extra/Assisted (kg)",
  "Per side": "Per zijde",
  "per side": "per zijde",
  "Per Side": "Per zijde",
  "Workouts": "Workouts",
  "Templates": "Sjablonen",
  "New Template": "Nieuw Sjabloon",
  "Template name is required.": "Sjabloonnaam is verplicht.",
  "Exercise Name": "Naam oefening",
  "Exercise name is required.": "Oefeningsnaam is verplicht.",
  "Edit Template": "Sjabloon Bewerken",
  "Create Template": "Sjabloon Aanmaken",
  "Sets": "Sets",
  "Reps": "Reps",
  "Weight": "Gewicht",
  "kg (optional)": "kg (optioneel)",
  "Optional": "Optioneel",
  "optional": "optioneel",
  "Exercises": "Oefeningen",
  "No exercises yet. Click \"Add\" to get started.": "Nog geen oefeningen. Klik op \"Toevoegen\" om te beginnen.",
  "Add exercise": "Oefening toevoegen",
  'Add "{name}"': 'Voeg "{name}" toe',
  "Start workout": "Start training",
  "Quick start": "Snelle start",
  "No templates yet.": "Nog geen sjablonen.",
  "Create your first template": "Maak je eerste sjabloon aan",
  "Active": "Actief",
  "Completed": "Voltooid",
  "No active sessions.": "Geen actieve trainingen.",
  "No completed sessions yet.": "Nog geen voltooide trainingen.",
  "Session": "Training",
  "Duration": "Duur",
  "Notes": "Notities",
  "Add note": "Notitie toevoegen",
  "No notes for this workout.": "Geen notities voor deze training.",
  "Complete workout": "Training afronden",
  "Finish": "Afronden",
  "Add set": "Set toevoegen",
  "Set": "Set",
  "Mark set as completed": "Markeer set als voltooid",
  "Complete": "Voltooid",
  "exercise": "oefening",
  "Next": "Volgende",
  "Previous": "Vorige",
  "Exercise": "Oefening",
  "Progress": "Voortgang",
  "History": "Geschiedenis",
  "Personal records": "Persoonlijke records",
  "Best set": "Beste set",
  "Total volume": "Totaal volume",
  "Sessions": "Sessies",
  "No data yet for this exercise.": "Nog geen gegevens voor deze oefening.",
  "Delete this workout?": "Deze training verwijderen?",
  "Delete this template?": "Dit sjabloon verwijderen?",
  "Back to templates": "Terug naar sjablonen",
  "Back to overview": "Terug naar overzicht",
  "Workout Studio Template": "Workout Studio Sjabloon",
  "Choose a template or start fresh": "Kies een sjabloon of begin leeg",
  "or": "of",
  "Start blank workout": "Begin lege training",
  "Started at": "Gestart op",
  "Completed at": "Voltooid op",
  "in progress": "bezig",
  "Toggle history": "Toon geschiedenis",
  "Remove": "Verwijderen",
  "A brief description...": "Een korte beschrijving...",
  "Sets must be at least 1.": "Sets moet minimaal 1 zijn.",
  "Reps must be at least 1.": "Herhalingen moeten minimaal 1 zijn.",
  "Failed to save template. Please try again.": "Sjabloon opslaan mislukt. Probeer het opnieuw.",
  "e.g. Full Body": "bijv. Full Body",
  "No exercises yet.": "Nog geen oefeningen.",
  "No exercises yet. Add one to start.": "Nog geen oefeningen. Voeg er een toe om te beginnen.",
  "Target muscle groups": "Doelspiergroepen",
  "Estimated time (minutes)": "Geschatte tijd (minuten)",
  "Estimated time": "Geschatte tijd",
  "min": "min",
  "Target": "Doel",
  "Done": "Klaar",
  "Finished": "Voltooid",
  "Workout title": "Trainingsnaam",
  "Edit Exercise": "Oefening bewerken",
  "Replace Exercise": "Oefening vervangen",
  "View History": "Geschiedenis bekijken",
  "Workout Review & Edits": "Training Beoordelen & Aanpassen",
  "Duration Editor": "Tijdsduur aanpassen",
  "Performance Summary": "Prestatiesamenvatting",
  "Total volume lifted": "Totaal volume getild",
  "PRs (Personal Records)": "Persoonlijke Records (PR's)",
  "New Record!": "Nieuw Record!",
  "Max weight": "Zwaarste set",
  "Max reps": "Meeste herhalingen",
  "Max sets": "Meeste sets",
  "Max volume": "Hoogste volume",
  "Max distance": "Grootste afstand",
  "Max duration": "Langste duur",
  "Total workout volume": "Totaal volume workout",
  "Workout duration": "Langste workout duur",
  "Exercises completed": "Meeste oefeningen",
  "was": "was",
  "Save": "Opslaan",
  "Discard Workout": "Training weggooien",
  "Are you sure you want to discard this workout session?": "Weet je zeker dat je deze training wilt weggooien?",
  "You have unfinished sets. Mark them as skipped or return to workout?": "Je hebt onafgeronde sets. Wil je deze markeren als overgeslagen of teruggaan naar de training?",
  "Return to workout": "Terug naar training",
  "Finish anyway": "Toch afronden",
  "History for {name}": "Geschiedenis van {name}",
  "Select Exercise to Replace": "Kies oefening ter vervanging",
  "Add Exercise": "Oefening toevoegen",
  "Hours": "Uur",
  "Minutes": "Min",
  "Seconds": "Sec",
  "Reorder": "Volgorde aanpassen",
  "Reorder Exercises": "Oefeningen herordenen",
  "Move Up": "Omhoog",
  "Move Down": "Omlaag",
  "Apply": "Toepassen",
  "Cancel": "Annuleren",
  "Last workout: today": "Laatste training: vandaag",
  "Last workout: yesterday": "Laatste training: gisteren",
  "Last workout: {days} days ago": "Laatste training: {days} dagen geleden",
  "Last workout: no workouts completed yet": "Laatste training: nog geen trainingen voltooid",
  "Total amount of exercises done": "Totaal aantal oefeningen gedaan",
  "Total volume moved": "Totaal volume verplaatst",
  "trainingen voltooid": "trainingen voltooid",
  "was je laatste training": "was je laatste training",
  "geleden was je laatste training": "geleden was je laatste training",
  "oefeningen gedaan": "oefeningen gedaan",
  "workouts gedaan": "workouts gedaan",
  "volume verplaatst": "volume verplaatst",
  "Leave Workout": "Training verlaten",
  "You are currently in an active workout. Are you sure you want to leave?": "Je bent momenteel bezig met een training. Weet je zeker dat je wilt weggaan?",
  "Leave": "Verlaten",
  "barbell": "Barbell",
  "dumbbell": "Dumbbell",
  "kettlebell": "Kettlebell",
  "cable": "Kabel",
  "machine": "Machine",
  "band": "Weerstandsband",
  "ball": "Bal",
  "none": "Geen",
  "Rest time (sec)": "Rusttijd (sec)",
  "Next milestone": "Volgende mijlpaal",
  "naar volgende mijlpaal": "tot volgende mijlpaal",
  "tot volgende mijlpaal": "tot volgende mijlpaal",
  "Rest": "Rusten",
  "Skip": "Overslaan",
  "Search exercises…": "Zoek oefeningen…",
  "Equipment": "Materiaal",
  "Rest Time": "Rusttijd",
  "Account": "Account",
  "Logged in as": "Ingelogd als",
  "Go to Workouts home": "Naar startpagina trainingen",
  "Go to Recipes home": "Naar startpagina recepten",
  "Resting": "Rusten",
  "seconds": "seconden",
  "sec": "sec",
  "Volume": "Volume",
  "Oefening": "Oefening",
  "All exercises completed!": "Alle oefeningen voltooid!",
  "Good job! Finish your workout to save your results.": "Goed gedaan! Rond je training af om de resultaten op te slaan.",
  "Lyric Quotes": "Lyric Quotes",
  "You": "You",
  "Bekijk quotes": "Bekijk quotes",
  "Poems for each other": "Poems",
  "Weight & Measurements": "Gewicht & Metingen",
  "Body": "Body",
  "body": "body",
  "Body measurements & progress tracking": "Lichaamsmetingen & voortgang",
  "Height (cm)": "Lengte (cm)",
  "Weight (kg)": "Gewicht (kg)",
  "Body fat (%)": "Vetpercentage (%)",
  "Skeletal muscle (kg)": "Skeletspier (kg)",
  "Fat mass (kg)": "Vetmassa (kg)",
  "Photos": "Foto's",
  "Log Entry": "Meting registreren",
  "+ meting": "+ meting",
  "Meting": "Meting",
  "meting": "meting",
  "Save Log": "Meting opslaan",
  "Delete Log": "Meting verwijderen",
  "Date": "Datum",
  "Latest log": "Laatste meting",
  "No measurements logged yet.": "Nog geen metingen geregistreerd.",
  "Track your physical progress": "Volg je fysieke voortgang",
  "Upload photo": "Foto uploaden",
  "Optimizing photo...": "Foto optimaliseren...",
  "Uploading photo...": "Foto uploaden...",
  "Failed to upload photo": "Foto uploaden mislukt",
  "Delete photo": "Foto verwijderen",
  "Are you sure you want to delete this log?": "Weet je zeker dat je deze meting wilt verwijderen?",
  "Height is automatically filled from previous log.": "Lengte is automatisch ingevuld op basis van de vorige meting.",
  "Body Fat": "Vet",
  "Skeletal Muscle": "Skeletspier",
  "Fat Mass": "Vetmassa",
  "Height": "Lengte",
  "Lichaamsmetingen": "Lichaamsmetingen",
  "Body Measurements": "Lichaamsmetingen",
  "+ Lichaamsmetingen toevoegen": "+ Lichaamsmetingen toevoegen",
  "Lichaamsmetingen verbergen": "Lichaamsmetingen verbergen",
  "Middel": "Middel",
  "Waist": "Middel",
  "Borst": "Borst",
  "Chest": "Borst",
  "Heupen": "Heupen",
  "Hips": "Heupen",
  "Biceps": "Biceps",
  "Biceps / Armen": "Biceps",
  "Bovenbenen": "Bovenbenen",
  "Thighs": "Bovenbenen",
  "Schouders": "Schouders",
  "Shoulders": "Schouders",
  "Nek": "Nek",
  "Neck": "Nek",
  "Kuiten": "Kuiten",
  "Calves": "Kuiten",
  "Sets with 0 reps": "Sets met 0 herhalingen",
  "You have completed sets with 0 reps. Do you want to finish anyway?": "Je hebt voltooide sets met 0 herhalingen. Wil je toch afronden?",

  "Wines": "Wijnen",
  "Wine": "Wijn",
  "New Wine": "Nieuwe Wijn",
  "Add Wine": "Wijn Toevoegen",
  "Edit Wine": "Wijn Bewerken",
  "Brand / Winery": "Merk / Wijnhuis",
  "Wine type": "Wijntype",
  "Variety / Grape": "Druif / Stijl",
  "Variety": "Druif / Stijl",
  "Vintage / Year": "Oogstjaar",
  "Country / Region": "Land / Streek",
  "Where bought": "Gekocht bij",
  "Purchase location": "Gekocht bij",
  "Select location": "Selecteer locatie",
  "Supermarket": "Supermarkt",
  "Wine shop": "Wijnwinkel",
  "Winery": "Wijnhuis",
  "Webshop / Online": "Webshop / Online",
  "Hospitality / Restaurant": "Horeca / Restaurant",
  "Gift": "Cadeau gekregen",
  "Other": "Overig",
  "supermarket": "Supermarkt",
  "wine_shop": "Wijnwinkel",
  "winery": "Wijnhuis",
  "online": "Webshop / Online",
  "restaurant": "Horeca / Restaurant",
  "gift": "Cadeau gekregen",
  "other": "Overig",
  "Notes / Why you liked it": "Notities / Waarom je deze lekker vond",
  "Label photo": "Foto van etiket",
  "Red": "Rood",
  "White": "Wit",
  "Rosé": "Rosé",
  "Sparkling": "Mousserend",
  "Dessert": "Dessertwijn",
  "red": "Rood",
  "white": "Wit",
  "rose": "Rosé",
  "sparkling": "Mousserend",
  "dessert": "Dessertwijn",
  "No wines yet.": "Nog geen wijnen.",
  "Add your first wine": "Voeg je eerste wijn toe",
  "Delete this wine?": "Deze wijn verwijderen?",
  "Save Wine": "Wijn Opslaan",
  "Saving wine...": "Wijn opslaan...",
  "Brand is required.": "Merk / Wijnhuis is verplicht.",
  "Variety is required.": "Druif / Stijl is verplicht.",
  "Background Settings": "Achtergrond instellingen",
  "Blur": "Vervaging",
  "Brightness": "Helderheid",
  "Background Image": "Achtergrond afbeelding",
  "Custom URL": "Aangepaste URL",
  "Upload Image": "Foto uploaden",
  "Reset to Default": "Herstel standaard",
  "Dark": "Donker",
  "Enter image URL...": "Voer afbeelding URL in...",

  "Cashflow": "Cashflow",
  "Facturatie": "Facturatie",
  "Dashboard": "Dashboard",
  "Projecten": "Projecten",
  "Facturen": "Facturen",
  "Klanten": "Klanten",
  "Handelsnamen": "Handelsnamen",
  "Nieuw project": "Nieuw project",
  "Nieuwe factuur": "Nieuwe factuur",
  "Nieuwe klant": "Nieuwe klant",
  "Nieuwe handelsnaam": "Nieuwe handelsnaam",
  "Project aanmaken": "Project aanmaken",
  "Klant aanmaken": "Klant aanmaken",
  "Handelsnaam aanmaken": "Handelsnaam aanmaken",
  "Factuur aanmaken": "Factuur aanmaken",
  "Omzet afgelopen 12 maanden": "Omzet afgelopen 12 maanden",
  "Openstaand": "Openstaand",
  "Concept": "Concept",
  "Betaald": "Betaald",
  "Verzonden": "Verzonden",
  "Te laat": "Te laat",
  "draft": "Concept",
  "sent": "Verzonden",
  "paid": "Betaald",
  "overdue": "Te laat",
  "one-time": "Eenmalig",
  "monthly": "Maandelijks",
  "Eenmalig": "Eenmalig",
  "Maandelijks": "Maandelijks",
  "Projecttype": "Projecttype",
  "Klant": "Klant",
  "Handelsnaam": "Handelsnaam",
  "Locatie": "Locatie",
  "Projectnaam": "Projectnaam",
  "Projectomschrijving": "Projectomschrijving",
  "Klantnaam": "Klantnaam",
  "Klantemail": "Klantemail",
  "Klantadres": "Klantadres",
  "Standaardtarief (€/uur)": "Standaardtarief (€/uur)",
  "Factuurnummer": "Factuurnummer",
  "Datum van facturering": "Datum van facturering",
  "Datum van dienstverlening": "Datum van dienstverlening",
  "Datum van verzending": "Datum van verzending",
  "Vervaldatum": "Vervaldatum",
  "KOR (Kleineondernemersregeling)": "KOR (Kleineondernemersregeling)",
  "KOR van toepassing": "KOR van toepassing",
  "Factuurregels": "Factuurregels",
  "Omschrijving": "Omschrijving",
  "Aantal": "Aantal",
  "Eenheidsprijs (€)": "Eenheidsprijs (€)",
  "Totaal (€)": "Totaal (€)",
  "Reiskosten": "Reiskosten",
  "Regel toevoegen": "Regel toevoegen",
  "Verwijder regel": "Verwijder regel",
  "Factuurtotaal": "Factuurtotaal",
  "Opslaan als concept": "Opslaan als concept",
  "Opslaan en verzenden": "Opslaan en verzenden",
  "Markeer als betaald": "Markeer als betaald",
  "PDF downloaden": "PDF downloaden",
  "PDF genereren...": "PDF genereren...",
  "Factuurdetails": "Factuurdetails",
  "Projectgegevens": "Projectgegevens",
  "Klantgegevens": "Klantgegevens",
  "Betalingsinformatie": "Betalingsinformatie",
  "Betalingsreferentie": "Betalingsreferentie",
  "IBAN": "IBAN",
  "KVK-nummer": "KVK-nummer",
  "BTW-nummer": "BTW-nummer",
  "Adres": "Adres",
  "Totaal te betalen": "Totaal te betalen",
  "Geen factuurregels.": "Geen factuurregels.",
  "Geen projecten gevonden.": "Geen projecten gevonden.",
  "Geen klanten gevonden.": "Geen klanten gevonden.",
  "Geen facturen gevonden.": "Geen facturen gevonden.",
  "Geen handelsnamen gevonden.": "Geen handelsnamen gevonden.",
  "Maak je eerste handelsnaam aan": "Maak je eerste handelsnaam aan",
  "Maak je eerste klant aan": "Maak je eerste klant aan",
  "Maak je eerste project aan": "Maak je eerste project aan",
  "Maak je eerste factuur aan": "Maak je eerste factuur aan",
  "Selecteer klant": "Selecteer klant",
  "Selecteer project": "Selecteer project",
  "Selecteer handelsnaam": "Selecteer handelsnaam",
  "Nieuwe klant aanmaken": "Nieuwe klant aanmaken",
  "Annuleer": "Annuleer",
  "Project bewerken": "Project bewerken",
  "Klant bewerken": "Klant bewerken",
  "Handelsnaam bewerken": "Handelsnaam bewerken",
  "Factuur bewerken": "Factuur bewerken",
  "Dit project verwijderen?": "Dit project verwijderen?",
  "Deze klant verwijderen?": "Deze klant verwijderen?",
  "Deze handelsnaam verwijderen?": "Deze handelsnaam verwijderen?",
  "Deze factuur verwijderen?": "Deze factuur verwijderen?",
  "Bezig met opslaan...": "Bezig met opslaan...",
  "Facturen ({count})": "Facturen ({count})",
  "Totaal gefactureerd": "Totaal gefactureerd",
  "Projectnaam is verplicht.": "Projectnaam is verplicht.",
  "Klantnaam is verplicht.": "Klantnaam is verplicht.",
  "Handelsnaam is verplicht.": "Handelsnaam is verplicht.",
  "Selecteer een klant.": "Selecteer een klant.",
  "Selecteer een project.": "Selecteer een project.",
  "Geen regels toegevoegd.": "Geen regels toegevoegd.",
  "Factuurnummer is verplicht.": "Factuurnummer is verplicht.",
  "Factuurnummer is al in gebruik": "Factuurnummer is al in gebruik",
  "Invoice number must be unique": "Factuurnummer is al in gebruik",
  "Prijs per eenheid (€)": "Prijs per eenheid (€)",
  "Prijs per eenheid": "Prijs per eenheid",
  "Uren": "Uren",
  "Dienst": "Dienst",
  "Korting": "Korting",
  "Percentage (%)": "Percentage (%)",
  "Bedrag (€)": "Bedrag (€)",
  "per uur": "per uur",
  "per km": "per km",
  "uur": "uur",
  "km": "km",

  "Rep Timer": "Rep Timer",
  "Start Timer": "Timer starten",
  "Pause": "Pauzeren",
  "Resume": "Hervatten",
  "Reset": "Resetten",
  "Finish & Save Set": "Voltooien & Set opslaan",
  "Complete Rep": "Rep voltooien",
  "Target Time": "Doeltijd",
  "Timed Rep": "Tijdsgebaseerde rep",
  "Reset to target time": "Streeftijd herstellen",
  "Save target time": "Doeltijd opslaan",
  "Save actual time": "Gemeten tijd opslaan",
  "Your account has been paused. Please contact an administrator.": "Uw account is gepauzeerd. Neem contact op met de beheerder.",
  "User Management & Monitoring": "Gebruikersbeheer & Monitoring",
  "Pause Account": "Account pauzeren",
  "Unpause Account": "Account hervatten",
  "Email Address": "E-mailadres",
  "Module Access": "Module toegang",
  "Last Login": "Laatst ingelogd",
  "Account Status": "Account status",
  "Paused": "Gepauzeerd",
  "Never": "Nooit",
  "Total Users": "Totaal gebruikers",
  "Active Users": "Actieve gebruikers",
  "Paused Accounts": "Gepauzeerde accounts",
  "Total Permissions": "Totaal permissies",
  "Search users...": "Zoek gebruikers...",
};



export function t(key: string, params?: Record<string, string>): string {
  let text = nl[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, v);
    }
  }
  return text;
}
