const nl: Record<string, string> = {
  "Recipe name is required.": "Receptnaam is verplicht.",
  "Failed to save recipe. Please try again.": "Recept opslaan mislukt. Probeer het opnieuw.",
  "Basic Info": "Basisgegevens",
  "Name": "Naam",
  "e.g. Grilled Chicken with Salsa": "bijv. Gegrilde Kip met Salsa",
  "Description": "Beschrijving",
  "A brief description of the dish...": "Een korte beschrijving van het gerecht...",
  "Details": "Details",
  "Cooking time (min)": "Bereidingstijd (min)",
  "Kitchen": "Keuken",
  "Status": "Status",
  "Rating": "Waardering",
  "Ingredients": "Ingrediënten",
  "Add": "Toevoegen",
  "No ingredients yet. Click \"Add\" to get started.": "Nog geen ingrediënten. Klik op \"Toevoegen\" om te beginnen.",
  "Qty": "Aantal",
  "Unit": "Eenheid",
  "Type": "Type",
  "Saving...": "Opslaan...",
  "Save Changes": "Wijzigingen Opslaan",
  "Create Recipe": "Recept Aanmaken",
  "to try": "proberen",
  "success": "geslaagd",
  "needs tweak": "aanpassen nodig",
  "failure": "mislukt",
  "archived": "gearchiveerd",
  "vegetable": "groente",
  "fruit": "fruit",
  "meat": "vlees",
  "fish": "vis",
  "spice": "kruiden",
  "liquid": "vloeistof",
  "dairy": "zuivel",
  "other": "overig",
  "pcs": "stuks",
  "tsp": "tl",
  "tbsp": "el",
  "pinch": "snufje",
  "User not found": "Gebruiker niet gevonden",
  "Wrong password": "Ongeldig wachtwoord",
  "Login failed. Please try again.": "Inloggen mislukt. Probeer het opnieuw.",
  "Username": "Gebruikersnaam",
  "Password": "Wachtwoord",
  "Logging in...": "Inloggen...",
  "Login": "Inloggen",
  "Logout": "Uitloggen",
  "Taste tracker": "Smaakmeter",
  "New Recipe": "Nieuw Recept",
  "All": "Alle",
  "No recipes yet.": "Nog geen recepten.",
  "Create your first recipe": "Maak je eerste recept aan",
  "No recipes with status \"{status}\".": "Geen recepten met status \"{status}\".",
  "Delete this recipe?": "Dit recept verwijderen?",
  "Edit": "Bewerk",
  "Delete": "Verwijder",
  "Ingredient": "Ingrediënt",
  "Quantity": "Hoeveelheid",
  "No ingredients listed.": "Geen ingrediënten vermeld.",
  "Back to recipe": "Terug naar recept",
  "Edit Recipe": "Recept Bewerken",
  "Search a kitchen…": "Zoek een keuken…",
  "Clear": "Wissen",
  "Welcome to": "Welkom bij",
  "Built for personal use and development": "Gemaakt voor persoonlijk gebruik en ontwikkeling",
  "Time": "Tijd",
  "Steps": "Stappen",
  "Add step": "Stap toevoegen",
  "No steps yet. Click \"Add step\" to get started.": "Nog geen stappen. Klik op \"Stap toevoegen\" om te beginnen.",
  "Step": "Stap",
  "g": "g",
  "kg": "kg",
  "ml": "ml",
  "l": "l",
};

export function t(key: string, params?: Record<string, string>): string {
  let text = nl[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, v);
    }
  }
  return text;
}
